# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/src_xdc.xdc

# IP: ip/memclk/memclk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==memclk || ORIG_REF_NAME==memclk} -quiet] -quiet
