# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/lhy/semester2-2/computer_organization/lab/CS214-Proj/proj.srcs/sources_1/ip/RAM_inst/RAM_inst.xci
# IP: The module: 'RAM_inst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/lhy/semester2-2/computer_organization/lab/CS214-Proj/proj.srcs/sources_1/ip/RAM_inst/RAM_inst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_inst'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/lhy/semester2-2/computer_organization/lab/CS214-Proj/proj.srcs/sources_1/ip/RAM_inst/RAM_inst.xci
# IP: The module: 'RAM_inst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/lhy/semester2-2/computer_organization/lab/CS214-Proj/proj.srcs/sources_1/ip/RAM_inst/RAM_inst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_inst'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
